### ISSUE TITLE
Parts from supported mods being thrown to the Lost and Found node

### ISSUE THREAD

**Issue by AlexSkylark** [hersfeldtn/GPTT#2]
While doing some tests, I noticed there were some parts being sent to the lost and found node that come from some mods featured in the list of supported ones. Those are the ones I could find:

### From DMagic Orbital Science (integration with US2): 
Universal Storage: SD4 Solar Particle Collector
Universal Storage: SD8 Soil Moisture Sensor
Universal Storage: SD1 Orbital Telescope
Universal Storage: SD3 RPWS Antenna
Universal Storage: SD2 Magnetometer Boom
Universal Storage: SD7 Multi-Spectral Imaging Platform
Universal Storage: SD6 GORESat
Universal Storage: SD5 ASERT

### From Kerbal Planetary Base Systems (integration wiht KIS and KAS): 
K&K Container: KIS (big)
K&K Container: KIS
K&K Ground Base [KIS]
K&K Storage: KIS
K&K Storage: KIS (big)
K&K Flexible Corridor

### From SCANSat:
SCAN Been There Done That®

### From Sterling Systems:
Upgrade Party

### From Universal Storage 2 (integration with KIS and KAS):
Universal Storage: T6 Surface Mountable KIS Container
Universal Storage: K51 Storage Inventory System

From a glance, the majority of those seem to be specific parts from supported mods that are loaded if and when another mod is also installed. Since those cases are of parts loaded when BOTH mods are in the supported list, I assume they should have been included in the tree. Those are the ones I found, but there's probably more, from supported mods not in my current install.

**Comment by hersfeldtn** [comment]
Think I've tracked these all down now
